### ISSUE TITLE
Translate title/abstract from source language

### ISSUE THREAD

**Issue by pvgenuchten** [soilwise-he/metadata-augmentation#4]
If a metadata has a non-english language, add a english translation. 

This should be prior to indexation, so any english filters also include this record Indicate on UI that translation is machine generated, with option to switch to original

Use [EU translation service](https://language-tools.ec.europa.eu/), google, deepl, ... or llm for translation

DoD
- [x] Implement API to call (EU) translation service
- [x] Update SWR data model to support translations
- [x] Develop translator component that can work at harvest time, in batch mode etc
- [x] Implement workflow for title/abstract translation
- [x] Show translations and indicator in catalogue UI
- [x] Operationalize and run translations

**Comment by pvgenuchten** [comment]
Runs as a micro service fetching strings from source database, stores its result in a translations table as hash, key, translation, language, if a hash is already in database returns instant translation

**Comment by robknapen** [comment]
These are two Python packages that it can be based on. They already cover a lot.

https://deep-translator.readthedocs.io/en/latest/?badge=latest
https://pypi.org/project/translators/

We would need to add an API, database, and external API key(s) (when using a payed service in the background).

**Comment by robknapen** [comment]
- EU translation service: https://language-tools.ec.europa.eu
- DeepL Translate API: https://www.deepl.com/en/pro-api?cta=header-pro-api

**Comment by pvgenuchten** [comment]
initial prototype of a service wrapper on top of EU service has been developed and deployed at https://api.soilwise-he.containers.wur.nl/translate/docs

**Comment by roblokers** [comment]
What still remains is to operationalize the translation, particularly how to setup the workflow and get the results to the UI

**Comment by roblokers** [comment]
DoD added to issue description

**Comment by robknapen** [comment]
I think setting up workflows and operationalisation of them is a bigger issue and discussion that needs happen before. E.g. do we base the whole system on an event bus, or service discovery, or batch processing and polling, and so on?

Definitely not something that can just be assigned to me :-) 

(Additionally: I am used to a Definition of Done to be more about quality aspects that indicate when an increment is complete. Not functional or component requirements. Those I consider to be a different thing.)
